{{ include('html.phtml') }}
<body class="min-vh-100 d-flex flex-column">
{{ include('header.phtml') }}

<main class="flex-grow-1">
    <div class="container-lg mt-3">
        <h1>Страница не найдена!</h1>
    <div class="align-items-lg-center">
    <h2 class="h2 mb-4">Ошибка 404</h2>
    <p class="mb-2">Поскольку мы не знаем, как и откуда вы попали на эту страницу, то рекомендуем начать <a href="/">с главной</a></p>
</main>

{{ include('footer.phtml') }}
</body>