{{ include('html.phtml') }}
<body class="min-vh-100 d-flex flex-column">
{{ include('header.phtml') }}
    <main class="flex-grow-1">
        <div class="container-lg mt-3">
            <h1>Сайты</h1>
            <div class="table-responsive">
                <table class="table table-bordered table-hover text-nowrap" data-test="urls">
                    <tbody>
                        <tr>
                            <th>ID</th>
                            <th>Имя</th>
                            <th>Последняя проверка</th>
                            <th>Код ответа</th>
                        </tr>
                        {% for site in allSites %}
                        <tr>
                            <td>{{ site.id }}</td>
                            <td><a href="/urls/{{ site.id }}">{{ site.name }}</a></td>
                            <td></td>
                            <td></td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </main>
{{ include('footer.phtml') }}
</body>