{{ include('html.phtml') }}
<body class="min-vh-100 d-flex flex-column">
{{ include('header.phtml') }}
{% for key, mMessages in messages  %}
    {% for message in mMessages %}
        <div {% if key == 'success' %}class="alert alert-success"{% elseif key == 'error' %}class="alert alert-danger"{% endif %} role="alert">{{ message|e }}</div>
    {% endfor %}
{% endfor %}
    <main class="flex-grow-1">
        <div class="container-lg mt-3">
            <h1>Сайт: {{ name }}</h1>
            <div class="table-responsive">
                <table class="table table-bordered table-hover text-nowrap" data-test="url">
                    <tbody>
                        <tr>
                            <td>ID</td>
                            <td>{{ id }}
                        </tr>
                        <tr>
                            <td>Имя</td>
                            <td>{{ name }}</td>
                        </tr>
                        <tr>
                            <td>Дата создания</td>
                            <td>{{ created_at }}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <h2 class="mt-5 mb-3">Проверки</h2>

            <form class="mb-3" method="post" action="/urls/{{ id }}/checks">
                <input type="submit" class="btn btn-primary" value="Запустить проверку">
            </form>

            <table class="table table-bordered table-hover" data-test="checks">
                <tbody>
                    <tr>
                        <th>ID</th>
                        <th>Код ответа</th>
                        <th>h1</th>
                        <th>title</th>
                        <th>description</th>
                        <th>Дата создания</th>
                    </tr>
                    {% for check in siteChecks %}
                    <tr>
                        <td>{{ check.id|e }}</td>
                        <td>{{ check.status_code|e }}</td>
                        <td>{{ check.h1|e }}</td>
                        <td>{{ check.title|e }}</td>
                        <td>{{ check.description|e }}</td>
                        <td>{{ check.created_at|e }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </main>
{{ include('footer.phtml') }}
</body>